Account
dnj/laravel-account pull request #2
Opened 2023-01-03 12:50 UTC by HamidNiakan

2023-01-04 06:26 UTC, yeganemehr requested changes

2023-01-04 06:26 UTC, yeganemehr commented on src/Http/Controllers/AccountController.php
> +	public function __construct ( AccountManager $account_manager ) {
```suggestion
	public function __construct ( protected AccountManager $accountManager ) {
```

We use php 8.1, you can code less.
for naming variables use camelCase

2023-01-04 06:26 UTC, yeganemehr commented on src/Http/Controllers/AccountController.php
> +		if ( !auth()->check() ) {
Do it as "auth" middleware in routes

2023-01-04 06:26 UTC, yeganemehr commented on src/Http/Controllers/AccountController.php
> +		$account = AccountResource::make($account);
just return the resource

2023-01-04 06:26 UTC, yeganemehr commented on src/routes/api.php
> +/*
Remove educational comments.

2023-01-04 06:26 UTC, yeganemehr commented on src/routes/api.php
> +		 Route::post('create' , 'create');
Read about RESTFUL url template
search => GET /accounts
create => POST /accounts
update => PUT /accounts/{accountId}
delete => DELETE /accounts/{accountId}

2023-01-08 14:56 UTC, yeganemehr requested changes

2023-01-08 14:56 UTC, yeganemehr commented on src/Http/Controllers/AccountController.php
> +    public function index(AccountSearchRequest $request)
please test this function

2023-01-08 14:56 UTC, yeganemehr commented on src/Http/Controllers/TransactionController.php
> +    public function index(Account $account, TransactionSearchRequest $request)
please test this method.

2023-01-15 05:22 UTC, HamidNiakan commented on src/Http/Controllers/AccountController.php
> +    public function index(AccountSearchRequest $request)
done

2023-01-15 13:34 UTC, HamidNiakan commented on src/Http/Controllers/TransactionController.php
> +    public function index(Account $account, TransactionSearchRequest $request)
done

2023-01-15 14:41 UTC, yeganemehr approved these changes

2023-01-15 14:42 UTC, merged