install UserLogger and use in models Account and Transaction
dnj/laravel-account pull request #9
Opened 2023-01-20 09:38 UTC by HamidNiakan

Install package UserLogger for saving user activites such as:
create account
update account
delete account
create transaction
update transaction
rollback transaction

2023-01-21 08:20 UTC, yeganemehr requested changes

2023-01-21 08:20 UTC, yeganemehr commented on src/Http/Controllers/AccountController.php
> +            ->log('create-account');
```suggestion
            ->log('create');
```

2023-01-21 08:20 UTC, yeganemehr commented on src/Http/Controllers/AccountController.php
> +            ->log('update-account');
```suggestion
            ->log('update');
```

2023-01-21 08:20 UTC, yeganemehr commented on src/Http/Controllers/AccountController.php
> +            ->log('delete-account');
```suggestion
            ->log('delete');
```

2023-01-21 08:20 UTC, yeganemehr commented on src/Http/Controllers/TransactionController.php
> +            ->log('create-transaction');
```suggestion
            ->log('create');
```

2023-01-21 08:20 UTC, yeganemehr commented on src/Http/Controllers/TransactionController.php
> +            ->log('update-transaction');
```suggestion
            ->log('update');
```

2023-01-21 08:20 UTC, yeganemehr commented on src/Http/Controllers/TransactionController.php
> +            ->log('rollback-transaction');
```suggestion
            ->log('rollback');
```

2023-01-21 08:28 UTC, HamidNiakan commented on src/Http/Controllers/TransactionController.php
> +            ->log('rollback-transaction');
done

2023-01-21 08:28 UTC, HamidNiakan commented on src/Http/Controllers/TransactionController.php
> +            ->log('update-transaction');
done

2023-01-21 08:28 UTC, HamidNiakan commented on src/Http/Controllers/TransactionController.php
> +            ->log('create-transaction');
done

2023-01-21 08:28 UTC, HamidNiakan commented on src/Http/Controllers/AccountController.php
> +            ->log('delete-account');
done

2023-01-21 08:29 UTC, HamidNiakan commented on src/Http/Controllers/AccountController.php
> +            ->log('update-account');
done

2023-01-21 08:29 UTC, HamidNiakan commented on src/Http/Controllers/AccountController.php
> +            ->log('create-account');
done

2023-01-31 13:41 UTC, yeganemehr approved these changes

2023-01-31 13:41 UTC, merged